# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoLaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField()),
                ('Humidity', models.FloatField()),
                ('Ppm', models.FloatField()),
                ('Wtr', models.IntegerField()),
                ('Lux', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoLaDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EUI', models.TextField(max_length=255)),
                ('Nickname', models.CharField(max_length=255)),
                ('FK_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loladata',
            name='FK_Device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Data.LoLaDevice'),
        ),
    ]
