# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0002_loladata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loladata',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
