# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0003_auto_20170711_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='loladevice',
            name='Battery',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
